name: Second Workflow

on:
  push:
    branches: [master, some_branch]
#  schedule:
#    - cron: '*/5 * * * *'

jobs:
  Linux-master:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Hello, World!
      run: |
        python ./someScript.py
    - name: Create cache file
      run: |
        mkdir check-SHA
        echo ${{ github.sha }} > github-sha.txt

    - name: Check SHA
      id: check_sha
      uses: actions/cache@v1
      with:
        path: check-SHA
        key: check-SHA-${{ github.sha }}
    
    - name: Some subsequent steps
      if: steps.check_sha.outputs.cache-hit != 'true'
      run: echo "This SHA is different from the cached SHA from the last run"

  Linux-some_branch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]
        
    steps:
      - uses: actions/checkout@v2
        with:
          ref: some_branch
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Hello, World!
        run: |
          python ./someScript.py
