name: Second Workflow

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Hello, World!
      run: |
        python ./someScript.py

  Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]
        
        steps:
          - uses: actions/checkout@v2
            with:
              ref: some_branch
          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
              python-version: ${{ matrix.python-version }}
          - name: Hello, World!
            run: |
              python ./someScript.py
